apiVersion: v1
kind: Pod
metadata:
  name: db-restore
spec:
  containers:
  - name: db-restore
    image: synyx/mysqldump-docker:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    env:
    - name: DB_NAME
      value: database
    - name: DB_HOST
      value: database_host
    - name: DB_USER
      value: database_user
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          key: mariadb-password
          name: database_password 
    volumeMounts:
    - mountPath: /mysqldump
      name: database-dump
      readOnly: true
  volumes:
  - name: database-dump-vol
    glusterfs:
      endpoints: gluster
      path: database-dump-store 
